### ISSUE TITLE
"About" page unavailable from "blog"

### ISSUE THREAD

**Issue by Slorany** [jscd/jscd.github.io#1]
Your "about" page seems to be a relative address adding "about/" at the end of the current page's address. When clicking on it from the "blog" page (whose address is "https://www.jscd.pw/n/"), it extends to "https://www.jscd.pw/n/about" which yields a 404.

The button works from the homepage though.

**Comment by jscd** [comment]
Oh thanks. The problem was the way I was doing the Javascript page transitions.
